### ISSUE TITLE
加入Gadget-Definition自动化部署

### ISSUE THREAD

**Issue by ZoruaFox** [TopRealm/InterfaceCodes#4]
目前阶段，如果在仓库中加入新的代码文件，仅能做到同步至MediaWiiki，但是不能自动修改Gadget-Definition，考虑加入相关功能，使其支持自动部署小工具定义

**Comment by Blossomstripe** [comment]
PR #6 理应解决了这一问题，现在需要进行一些测试 @ZoruaFox 。

**Comment by ZoruaFox** [comment]
> PR #6 理应解决了这一问题，现在需要进行一些测试 @ZoruaFox 。

Hang on for a moment, doing homework()

**Comment by Blossomstripe** [comment]
Issue resolved.
